### ISSUE TITLE
IndexOutOfBoundsException in Populating vertex array

### ISSUE THREAD

**Issue by SagarKhurana** [andresoviedo/android-3D-model-viewer#102]
```
index=-300 out of bounds (limit=103359)
    java.lang.IndexOutOfBoundsException: index=-300 out of bounds (limit=103359)
        at java.nio.Buffer.checkIndex(Buffer.java:528)
        at java.nio.ByteBufferAsFloatBuffer.get(ByteBufferAsFloatBuffer.java:96)
        at org.andresoviedo.app.model3D.model.Object3DBuilder.generateArrays(Object3DBuilder.java:522)
        at org.andresoviedo.app.model3D.services.wavefront.WavefrontLoaderTask.build(WavefrontLoaderTask.java:78)
        at org.andresoviedo.app.model3D.services.LoaderTask.doInBackground(LoaderTask.java:60)
        at org.andresoviedo.app.model3D.services.LoaderTask.doInBackground(LoaderTask.java:17)
        at android.os.AsyncTask$2.call(AsyncTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)
```

I tried to load one of my 3d models and got this error.
below is some information:
```
I/WavefrontLoader: Number of vertices:34453
I/WavefrontLoader: Number of faces:61099
I/WavefrontLoader: No. of vertices: 34453
I/WavefrontLoader: No. of normal coords: 7334
I/WavefrontLoader: No. of tex coords: 47614
I/WavefrontLoader: No. of faces: 61099
I/WavefrontLoader: No materials available
I/System.out: No. of materials used: 0
I/ContentUtils: Opening stream /storage/emulated/0/images/Arnsberg_Building.obj
I/System.out: Using 3D tex coords: true

```

Can you please help me out.

**Comment by andresoviedo** [comment]
HI.  Current code does not match the pointed out line.
Please, Is it possible for you to share your model so I can take a look?
Regards

**Comment by SagarKhurana** [comment]
Hi @andresoviedo, sorry but I cannot provide this 3d model currently, but I do have a sample 3d model which is also getting the same error. 
please find the[ teapot_multimat.obj ](https://drive.google.com/open?id=1g3ByjDwpALvftoEqc1aNPyat6Isq1fFt) and its .mtl file for the reference. 

below are the error log and more information about the model.

Error Log. 

```
index=-4797 out of bounds (limit=4794)
    java.lang.IndexOutOfBoundsException: index=-4797 out of bounds (limit=4794)
        at java.nio.Buffer.checkIndex(Buffer.java:528)
        at java.nio.ByteBufferAsFloatBuffer.get(ByteBufferAsFloatBuffer.java:96)
        at org.andresoviedo.android_3d_model_engine.services.Object3DBuilder.generateArrays(Object3DBuilder.java:416)
        at org.andresoviedo.android_3d_model_engine.services.wavefront.WavefrontLoaderTask.build(WavefrontLoaderTask.java:78)
        at org.andresoviedo.android_3d_model_engine.services.LoaderTask.doInBackground(LoaderTask.java:60)
        at org.andresoviedo.android_3d_model_engine.services.LoaderTask.doInBackground(LoaderTask.java:17)
        at android.os.AsyncTask$2.call(AsyncTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)
```

Model Information:

```
I/WavefrontLoader: Number of vertices:1598
I/WavefrontLoader: Number of faces:3080
I/WavefrontLoader: No. of vertices: 1598
I/WavefrontLoader: No. of normal coords: 1598
I/WavefrontLoader: No. of tex coords: 809
I/WavefrontLoader: No. of faces: 3080
I/WavefrontLoader: No materials available
I/System.out: No. of materials used: 0
I/ContentUtils: Opening stream /storage/emulated/0/images/teapot_multimat.obj
```

**Comment by andresoviedo** [comment]
Hi.  Fixed in latest version.  Please give it a try.
Regards
