### ISSUE TITLE
Cannot load dae 3d model with animation

### ISSUE THREAD

**Issue by SagarKhurana** [andresoviedo/android-3D-model-viewer#132]
Hey Andres, 

I have checked the other issues too, in your repo, tried with the latest version as well.
but the issue is still the same.
Can you help us out here.
I am facing difficulty in rendering the **dae 3d object with animation**, I referred your others issuelike [88](https://github.com/andresoviedo/android-3D-model-viewer/issues/88) and I am able to render that baby groot. 
 
below is the error log.

`2020-01-13 12:12:30.001 3754-29041/? E/SceneLoader: Attempt to invoke virtual method 'org.andresoviedo.android_3d_model_engine.services.collada.entities.JointData org.andresoviedo.android_3d_model_engine.services.collada.entities.SkeletonData.find(java.lang.String)' on a null object reference
    java.lang.NullPointerException: Attempt to invoke virtual method 'org.andresoviedo.android_3d_model_engine.services.collada.entities.JointData org.andresoviedo.android_3d_model_engine.services.collada.entities.SkeletonData.find(java.lang.String)' on a null object reference
        at org.andresoviedo.android_3d_model_engine.services.collada.loader.GeometryLoader.extractModelData(GeometryLoader.java:161)
        at org.andresoviedo.android_3d_model_engine.services.collada.loader.ColladaLoader.loadColladaModel(ColladaLoader.java:210)
        at org.andresoviedo.android_3d_model_engine.services.collada.loader.ColladaLoader.buildAnimatedModel(ColladaLoader.java:52)
        at org.andresoviedo.android_3d_model_engine.services.collada.ColladaLoaderTask.build(ColladaLoaderTask.java:27)
        at org.andresoviedo.android_3d_model_engine.services.LoaderTask.doInBackground(LoaderTask.java:59)
        at org.andresoviedo.android_3d_model_engine.services.LoaderTask.doInBackground(LoaderTask.java:17)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)`

Unfortunately I cannot provide you the 3d object, But I will provide your the config if your require. 

Looking forward for your help :)

**Comment by andresoviedo** [comment]
Hello @SagarKhurana 
I am preparing a new Release.  I have fixed several issues.
If you are ok, I will let you know so you can test again if you want.
Thanks for your feedback.

**Comment by andresoviedo** [comment]
Hello.  New version available.
Please give it a try.
If you still have issues please reopen ticket
regards
