### ISSUE TITLE
Error loading model on Android 7.1.0

### ISSUE THREAD

**Issue by MartSerra** [andresoviedo/android-3D-model-viewer#18]
I try to load the Plane.obj model in examples on an Android device running **API 25 Nougat 7.1.0** but I get this error.
`There was a problem building the model: index=704643072 out of bounds (limit=1686)`
![alt text](http://i.imgur.com/imMJuLi.png "Android Error")
This error happens only on this version of Android.

Here it is the Log:
```java
04-20 13:03:18.539 1414-1863/org.andresoviedo.dddmodel2 E/Object3DBuilder: index=704643072 out of bounds (limit=1686)
                                                                           java.lang.IndexOutOfBoundsException: index=704643072 out of bounds (limit=1686)
                                                                               at java.nio.Buffer.checkIndex(Buffer.java:528)
                                                                               at java.nio.ByteBufferAsFloatBuffer.get(ByteBufferAsFloatBuffer.java:95)
                                                                               at org.andresoviedo.app.model3D.model.Object3DBuilder.generateArrays(Object3DBuilder.java:466)
                                                                               at org.andresoviedo.app.model3D.services.wavefront.WavefrontLoader2$1.build(WavefrontLoader2.java:106)
                                                                               at org.andresoviedo.app.model3D.controller.LoaderTask.doInBackground(LoaderTask.java:92)
                                                                               at org.andresoviedo.app.model3D.controller.LoaderTask.doInBackground(LoaderTask.java:22)
                                                                               at android.os.AsyncTask$2.call(AsyncTask.java:305)
                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                               at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                               at java.lang.Thread.run(Thread.java:761)
04-20 13:03:18.559 1414-1429/org.andresoviedo.dddmodel2 E/EGL_emulation: tid 1429: eglSurfaceAttrib(1174): error 0x3009 (EGL_BAD_MATCH)
04-20 13:03:18.559 1414-1429/org.andresoviedo.dddmodel2 W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xcefd2aa0, error=EGL_BAD_MATCH
04-20 13:03:18.621 1414-1429/org.andresoviedo.dddmodel2 E/EGL_emulation: tid 1429: eglSurfaceAttrib(1174): error 0x3009 (EGL_BAD_MATCH)
04-20 13:03:18.621 1414-1429/org.andresoviedo.dddmodel2 W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xe427eb40, error=EGL_BAD_MATCH
                                                                          [ 04-20 13:03:18.844  1414: 1862 D/         ]
                                                                          HostConnection::get() New Host Connection established 0xd05ac340, tid 1862
04-20 13:03:18.988 1414-1862/org.andresoviedo.dddmodel2 D/org.andresoviedo.app.model3D.view.ModelRenderer: projection: [-0.6728972,0.6728972,-1,1]-near/far[1,10]
04-20 13:03:19.706 1414-1414/org.andresoviedo.dddmodel2 E/SceneLoader: index=704643072 out of bounds (limit=1686)
                                                                       java.lang.IndexOutOfBoundsException: index=704643072 out of bounds (limit=1686)
                                                                           at java.nio.Buffer.checkIndex(Buffer.java:528)
                                                                           at java.nio.ByteBufferAsFloatBuffer.get(ByteBufferAsFloatBuffer.java:95)
                                                                           at org.andresoviedo.app.model3D.model.Object3DBuilder.generateArrays(Object3DBuilder.java:466)
                                                                           at org.andresoviedo.app.model3D.services.wavefront.WavefrontLoader2$1.build(WavefrontLoader2.java:106)
                                                                           at org.andresoviedo.app.model3D.controller.LoaderTask.doInBackground(LoaderTask.java:92)
                                                                           at org.andresoviedo.app.model3D.controller.LoaderTask.doInBackground(LoaderTask.java:22)
                                                                           at android.os.AsyncTask$2.call(AsyncTask.java:305)
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                           at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                           at java.lang.Thread.run(Thread.java:761)
```

Thanks for the help 😄

**Comment by andresoviedo** [comment]
Hi @MartSerra . Please try the latest release. I dont have physical 7 device, but I tested in on Virtual device 7.1.1. Hope it works for you. If you still have problems please reopen the issue.
Kind regards

**Comment by MartSerra** [comment]
Thanks @andresoviedo this update fix the problem with Android 7 Nougat, thanks for your support. 😄
