### ISSUE TITLE
java.lang.RuntimeException: glGetUniformLocation: glError 1280

### ISSUE THREAD

**Issue by alexdar94** [andresoviedo/android-3D-model-viewer#19]
Hi Andres, I am new to OpenGL and I'm using your code for a school project. I want to load ship.obj. Object3DImpl.setMvpMatrix has raised error `java.lang.RuntimeException: glGetUniformLocation: glError 1280`. Can you give me some hints, what could have caused it to happen? 

Error stack trace:
```
java.lang.RuntimeException: glGetUniformLocation: glError 1280
at com.myproject.model3D.util.GLUtil.checkGlError(GLUtil.java:162)
at com.myproject.model3D.model.Object3DImpl.setMvpMatrix(Object3DImpl.java:150)
at com.myproject.model3D.model.Object3DImpl.draw(Object3DImpl.java:64)
at com.myproject.model3D.model.Object3DImpl.draw(Object3DImpl.java:48)
at com.myproject.ModelRenderer.onDrawFrame(ModelRenderer.java:133)
at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1522)
at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
```

Thank you.

**Comment by alexdar94** [comment]
Hi, I have found out that these lines of my code in `onSurfaceChanged ` have caused the error. The code is to set SurfaceView background to transparent.

```
gl.glDisable(GL10.GL_DITHER);
        gl.glHint(GL10.GL_PERSPECTIVE_CORRECTION_HINT,
                GL10.GL_FASTEST);

        gl.glClearColor(0,0,0,0);
        gl.glEnable(GL10.GL_CULL_FACE);
        gl.glShadeModel(GL10.GL_SMOOTH);
        gl.glEnable(GL10.GL_DEPTH_TEST);
```

May I know how can I set the background of SurfaceView to transparent?

Thank you.

**Comment by alexdar94** [comment]
After some research, I was able to get it done by adding:

ModelSurfaceView:
```
setEGLConfigChooser(8, 8, 8, 8, 16, 0);
getHolder().setFormat(PixelFormat.TRANSLUCENT);
```

ModelRenderer: onSurfaceCreated()
`GLES20.glClearColor(0.0f, 0.0f, 0.0f, 0.0f);`

Thank you!
