### ISSUE TITLE
App crashes if we zoom in too much or zoom out too much

### ISSUE THREAD

**Issue by omkarkhalipe** [andresoviedo/android-3D-model-viewer#24]
If I zoom in too much or zoom out too much the app crashes. Can we give a zoom limit so that we can avoid crashes

**Comment by andresoviedo** [comment]
Do you still have this issue with the latest apk?

**Comment by alamkaruna** [comment]
hello andrea oviedo, I've used a few moments of your latest release app, but I still find the same bug as described by @omkarkhalipe

I think this bug is not correct "fixed,
I aan tell a little where the bugs are located can be fixed as soon as possible


Expected behavior
I'm trying to open the 3D model viewer app I'm trying to enlarge the 3D image it should work fine without going out to the app's main page, I hope this feature works fine without having to go back to the app's main screen , I hope this bug is fixed.

Actual behavior
after I open the 3D model viewer app I am trying to enlarge the default image from the app, after I zoom in on the MODELS option
feature does not return me to the main view of the app, but after I select the DEMO option
I tried enlarging the image but the app took me back to the main page of the app

How to reproduce
first of all you download the app after downloading your application open it after you see the basic app you opened DEMO option after that you try to enlarge the 3D image object

Browser : 3D model viewer Version 2.0.1
Operating system: android 7.0
Smartphone : Oppo A71


Recording of the bug

https://youtu.be/ZqBhHiPwTEw

hope this can help thank you

**Comment by andresoviedo** [comment]
Thank you @alamkaruna.
It seems that the demo is crashing.
It is possible that you attach the log?
I'm gonna try to reproduce it myself.

**Comment by espoem** [comment]
Hello @andresoviedo , I have seen your issue in here and wanted to help you to get the log of the problem. You have had this issue reported in #34 .

```
05-09 09:44:22.335 27185 27216 E Object3DBuilder: Failure to load texture coordinates
05-09 09:44:22.335 27185 27216 E Object3DBuilder: java.lang.IndexOutOfBoundsException: index=-2 out of bounds (limit=4330)
05-09 09:44:22.335 27185 27216 E Object3DBuilder: 	at java.nio.Buffer.checkIndex(Buffer.java:528)
05-09 09:44:22.335 27185 27216 E Object3DBuilder: 	at java.nio.ByteBufferAsFloatBuffer.get(ByteBufferAsFloatBuffer.java:95)
05-09 09:44:22.335 27185 27216 E Object3DBuilder: 	at org.andresoviedo.app.model3D.model.Object3DBuilder.generateArrays(Object3DBuilder.java:659)
05-09 09:44:22.335 27185 27216 E Object3DBuilder: 	at org.andresoviedo.app.model3D.model.Object3DBuilder.loadV5(Object3DBuilder.java:407)
05-09 09:44:22.335 27185 27216 E Object3DBuilder: 	at org.andresoviedo.app.model3D.services.ExampleSceneLoader$1.doInBackground(ExampleSceneLoader.java:82)
05-09 09:44:22.335 27185 27216 E Object3DBuilder: 	at org.andresoviedo.app.model3D.services.ExampleSceneLoader$1.doInBackground(ExampleSceneLoader.java:38)
05-09 09:44:22.335 27185 27216 E Object3DBuilder: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
05-09 09:44:22.335 27185 27216 E Object3DBuilder: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-09 09:44:22.335 27185 27216 E Object3DBuilder: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
05-09 09:44:22.335 27185 27216 E Object3DBuilder: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
05-09 09:44:22.335 27185 27216 E Object3DBuilder: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
05-09 09:44:22.335 27185 27216 E Object3DBuilder: 	at java.lang.Thread.run(Thread.java:761)
05-09 09:44:23.819 27185 27185 E Example : Attempt to invoke virtual method 'java.io.InputStream android.content.res.AssetManager.open(java.lang.String)' on a null object reference
05-09 09:44:23.819 27185 27185 E Example : java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.InputStream android.content.res.AssetManager.open(java.lang.String)' on a null object reference
05-09 09:44:23.819 27185 27185 E Example : 	at org.andresoviedo.app.util.url.android.Handler$ClasspathURLConnection.connect(Handler.java:74)
05-09 09:44:23.819 27185 27185 E Example : 	at org.andresoviedo.app.util.url.android.Handler$ClasspathURLConnection.getInputStream(Handler.java:82)
05-09 09:44:23.819 27185 27185 E Example : 	at java.net.URL.openStream(URL.java:1057)
05-09 09:44:23.819 27185 27185 E Example : 	at org.andresoviedo.app.model3D.services.collada.loader.ColladaLoader.buildAnimatedModel(ColladaLoader.java:56)
05-09 09:44:23.819 27185 27185 E Example : 	at org.andresoviedo.app.model3D.services.collada.loader.ColladaLoader.load(ColladaLoader.java:164)
05-09 09:44:23.819 27185 27185 E Example : 	at org.andresoviedo.app.model3D.services.ExampleSceneLoader$1.doInBackground(ExampleSceneLoader.java:191)
05-09 09:44:23.819 27185 27185 E Example : 	at org.andresoviedo.app.model3D.services.ExampleSceneLoader$1.doInBackground(ExampleSceneLoader.java:38)
05-09 09:44:23.819 27185 27185 E Example : 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
05-09 09:44:23.819 27185 27185 E Example : 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-09 09:44:23.819 27185 27185 E Example : 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
05-09 09:44:23.819 27185 27185 E Example : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
05-09 09:44:23.819 27185 27185 E Example : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
05-09 09:44:23.819 27185 27185 E Example : 	at java.lang.Thread.run(Thread.java:761)
05-09 09:45:48.274 27185 27185 E MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'float[] org.andresoviedo.app.model3D.entities.BoundingBox.getCenter()' on a null object reference
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at org.andresoviedo.app.model3D.controller.TouchController.selectObjectImpl(TouchController.java:321)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at org.andresoviedo.app.model3D.controller.TouchController.onTouchEvent(TouchController.java:188)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at org.andresoviedo.app.model3D.view.ModelSurfaceView.onTouchEvent(ModelSurfaceView.java:42)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at android.view.View.dispatchTouchEvent(View.java:10146)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2745)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2385)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2745)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2385)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2745)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2385)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:437)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1834)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at android.app.Activity.dispatchTouchEvent(Activity.java:3067)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:399)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at android.view.View.dispatchPointerEvent(View.java:10377)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4973)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4798)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4304)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4357)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4323)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4470)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4331)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4527)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4304)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4357)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4323)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4331)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4304)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6894)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6868)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6811)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7066)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at android.os.MessageQueue.nativePollOnce(Native Method)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at android.os.MessageQueue.next(MessageQueue.java:328)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at android.os.Looper.loop(Looper.java:148)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at android.app.ActivityThread.main(ActivityThread.java:6297)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at java.lang.reflect.Method.invoke(Native Method)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
05-09 09:45:48.276 27185 27185 E MessageQueue-JNI: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: FATAL EXCEPTION: main
05-09 09:45:48.277 27185 27185 E AndroidRuntime: Process: org.andresoviedo.dddmodel2, PID: 27185
05-09 09:45:48.277 27185 27185 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'float[] org.andresoviedo.app.model3D.entities.BoundingBox.getCenter()' on a null object reference
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at org.andresoviedo.app.model3D.controller.TouchController.selectObjectImpl(TouchController.java:321)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at org.andresoviedo.app.model3D.controller.TouchController.onTouchEvent(TouchController.java:188)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at org.andresoviedo.app.model3D.view.ModelSurfaceView.onTouchEvent(ModelSurfaceView.java:42)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at android.view.View.dispatchTouchEvent(View.java:10146)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2745)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2385)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2745)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2385)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2745)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2385)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:437)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1834)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at android.app.Activity.dispatchTouchEvent(Activity.java:3067)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:399)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:10377)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4973)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4798)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4304)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4357)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4323)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4470)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4331)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4527)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4304)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4357)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4323)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4331)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4304)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6894)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6868)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6811)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7066)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at android.os.MessageQueue.nativePollOnce(Native Method)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at android.os.MessageQueue.next(MessageQueue.java:328)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6297)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
05-09 09:45:48.277 27185 27185 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
```

**Comment by alamkaruna** [comment]
<code>nsjab</code>

**Comment by andresoviedo** [comment]
It should be fixed in latest version. If it doesn't, please reopen issue.
