### ISSUE TITLE
Transparent Background

### ISSUE THREAD

**Issue by darwinfrancis** [andresoviedo/android-3D-model-viewer#31]
How can make the ModelSurfaceView  background transparent. now it displays all models in a dark background. i have tried using

        setZOrderOnTop(true);
        setEGLConfigChooser(8, 8, 8, 8, 16, 0);
        getHolder().setFormat(PixelFormat.TRANSPARENT);

nothing works.

please guide me to make the ModelSurfaceView  background as transparent.

**Comment by andresoviedo** [comment]
Have you tried this in the ModelRenderer?

GLES20.glClearColor(0.0f, 0.0f, 0.0f, 0.0f)

Have you make the activity transparent?

https://stackoverflow.com/questions/2176922/how-do-i-create-a-transparent-activity-on-android

**Comment by darwinfrancis** [comment]
hi @andresoviedo 
i want to get the view with transparent background.    
      <org.andresoviedo.app.model3D.view.ModelSurfaceView
        android:id="@+id/surface_view"
        android:layout_width="250dp"
        android:layout_height="250dp"
        android:layout_gravity="center"
        android:background="@android:color/transparent"/>

my layout contains a camera view and org.andresoviedo.app.model3D.view.ModelSurfaceView, i want to place the 3d model above camera view with transparent background.

<img width="400" alt="arcore" src="https://user-images.githubusercontent.com/6102490/34930760-251c5d0a-f9f1-11e7-86b3-a705a5a1a8c2.png">
i want something like this.

**Comment by darwinfrancis** [comment]
Got it working

1) add the below lines of code at bottom of onSurfaceCreated method of ModelRenderer class.
    
                gl.glDisable(GL10.GL_DITHER);
		gl.glHint(GL10.GL_PERSPECTIVE_CORRECTION_HINT,
				GL10.GL_FASTEST);

		gl.glClearColor(0,0,0,0);
		gl.glEnable(GL10.GL_CULL_FACE);
		gl.glShadeModel(GL10.GL_SMOOTH);
		gl.glEnable(GL10.GL_DEPTH_TEST);

2) add the following code at init() function of ModelSurfaceView (just before setRenderer(mRenderer);)
               getHolder().setFormat(PixelFormat.RGBA_8888);
               getHolder().setFormat(PixelFormat.TRANSLUCENT);
               setRenderMode(GLSurfaceView.RENDERMODE_CONTINUOUSLY);

**Comment by andresoviedo** [comment]
Great. Thanks for the feedback

**Comment by sdaduanbilei** [comment]
@darwinfrancis 
1. change ```ModelActivity```  ```setContentView```
 
```<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical" android:layout_width="match_parent"
    android:layout_height="match_parent">

    <ImageView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@android:color/white"
        android:src="@drawable/ic_launcher"
        />

    <org.andresoviedo.app.model3D.view.ModelSurfaceView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/model_view"
        />

</FrameLayout>
```
2 Get the following error message.
```Process: org.andresoviedo.dddmodel2, PID: 7644
                                                                          java.lang.RuntimeException: Unable to start activity ComponentInfo{org.andresoviedo.dddmodel2/org.andresoviedo.app.model3D.view.ModelActivity}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class org.andresoviedo.app.model3D.view.ModelSurfaceView
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                                              at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                              at android.os.Looper.loop(Looper.java:164)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                           Caused by: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class org.andresoviedo.app.model3D.view.ModelSurfaceView
                                                                           Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class org.andresoviedo.app.model3D.view.ModelSurfaceView
                                                                           Caused by: java.lang.NoSuchMethodException: <init> [class android.content.Context, interface android.util.AttributeSet]
                                                                              at java.lang.Class.getConstructor0(Class.java:2320)
                                                                              at java.lang.Class.getConstructor(Class.java:1725)
                                                                              at android.view.LayoutInflater.createView(LayoutInflater.java:615)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
                                                                              at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                              at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:418)
                                                                              at android.app.Activity.setContentView(Activity.java:2654)
                                                                              at org.andresoviedo.app.model3D.view.ModelActivity.onCreate(ModelActivity.java:62)
                                                                              at android.app.Activity.performCreate(Activity.java:6975)
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                                              at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                              at android.os.Looper.loop(Looper.java:164)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

Ask for your guidance.

**Comment by darwinfrancis** [comment]
@sdaduanbilei  You have a custom ModelSurfaceView view referenced in your layout XML, and the custom view doesn't have the required public constructor that takes in Context,AttributeSet arguments.

modify the ModelSurfaceView  class as below

1) add the below constructor in ModelSurfaceView  class
  ```
public ModelSurfaceView(Context context, AttributeSet attrs) {
        super(context, attrs);
    }
```

2) remove the existing constructor 
`public ModelSurfaceView(ModelActivity parent) ` from ModelSurfaceView   class

3) add a initialization method in ModelSurfaceView

```
public void init(UIARView parent) {
        // parent component
        this.parent = parent;
        // Create an OpenGL ES 2.0 context.
        setEGLContextClientVersion(2);

        setEGLConfigChooser(8, 8, 8, 8, 16, 0);
        // This is the actual renderer of the 3D space
        mRenderer = new ModelRenderer(this);

        // added for transparency
        setEGLConfigChooser(8, 8, 8, 8, 16, 0);
        //getHolder().setFormat(PixelFormat.TRANSLUCENT);
        setZOrderOnTop(true);

        setRenderer(mRenderer);

        //getHolder().setFormat(PixelFormat.RGBA_8888);
        getHolder().setFormat(PixelFormat.TRANSLUCENT);
        setRenderMode(GLSurfaceView.RENDERMODE_CONTINUOUSLY);

        // Render the view only when there is a change in the drawing data
        // TODO: enable this again
        // setRenderMode(GLSurfaceView.RENDERMODE_WHEN_DIRTY);
        touchHandler = new TouchController(this, mRenderer);
    }
```

4) then call `modelSurfaceView.init(this);` in your activity

**Comment by sdaduanbilei** [comment]
@darwinfrancis 
Thank you very much, 666! I want to know how you implemented the camera preview.

**Comment by darwinfrancis** [comment]
@Venoli you don't need to pass any value to AttributeSet , the constructor automatically get called.

**Comment by Venoli** [comment]
@darwinfrancis
Thank you very much!
