### ISSUE TITLE
touch control

### ISSUE THREAD

**Issue by AAlier** [andresoviedo/android-3D-model-viewer#39]
6/org.andresoviedo.dddmodel2 E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
01-31 15:03:35.097 11356-11356/org.andresoviedo.dddmodel2 E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
                                                                                  at org.andresoviedo.app.model3D.collision.CollisionDetection.getBoxIntersection(CollisionDetection.java:52)
                                                                                  at org.andresoviedo.app.model3D.collision.CollisionDetection.getBoxIntersection(CollisionDetection.java:37)
                                                                                  at org.andresoviedo.app.model3D.services.SceneLoader.processTouch(SceneLoader.java:323)
                                                                                  at org.andresoviedo.app.model3D.controller.TouchController.onTouchEvent(TouchController.java:189)
                                                                                  at org.andresoviedo.app.model3D.view.ModelSurfaceView.onTouchEvent(ModelSurfaceView.java:42)
                                                                                  at android.view.View.dispatchTouchEvent(View.java:9993)
                                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
                                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
                                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
                                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
                                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
                                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
                                                                                  at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2831)
                                                                                  at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1863)
                                                                                  at android.app.Activity.dispatchTouchEvent(Activity.java:3046)
                                                                                  at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2792)
                                                                                  at android.view.View.dispatchPointerEvent(View.java:10228)
                                                                                  at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5344)
                                                                                  at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5180)
                                                                                  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4620)
                                                                                  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4673)
                                                                                  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4639)
                                                                                  at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4781)
                                                                                  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4647)
                                                                                  at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4838)
                                                                                  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4620)
                                                                                  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4673)
                                                                                  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4639)
                                                                                  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4647)
                                                                                  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4620)
                                                                                  at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7306)
                                                                                  at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7184)
                                                                                  at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7145)
                                                                                  at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7416)
                                                                                  at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                                  at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                  at android.os.MessageQueue.next(MessageQueue.java:323)
                                                                                  at android.os.Looper.loop(Looper.java:143)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
01-31 15:03:35.097 11356-11356/org.andresoviedo.dddmodel2 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: org.andresoviedo.dddmodel2, PID: 11356
                                                                            java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
                                                                                at org.andresoviedo.app.model3D.collision.CollisionDetection.getBoxIntersection(CollisionDetection.java:52)
                                                                                at org.andresoviedo.app.model3D.collision.CollisionDetection.getBoxIntersection(CollisionDetection.java:37)
                                                                                at org.andresoviedo.app.model3D.services.SceneLoader.processTouch(SceneLoader.java:323)
                                                                                at org.andresoviedo.app.model3D.controller.TouchController.onTouchEvent(TouchController.java:189)
                                                                                at org.andresoviedo.app.model3D.view.ModelSurfaceView.onTouchEvent(ModelSurfaceView.java:42)
                                                                                at android.view.View.dispatchTouchEvent(View.java:9993)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
                                                                                at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
                                                                                at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
                                                                                at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2831)
                                                                                at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1863)
                                                                                at android.app.Activity.dispatchTouchEvent(Activity.java:3046)
                                                                                at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2792)
                                                                                at android.view.View.dispatchPointerEvent(View.java:10228)
                                                                                at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5344)
                                                                                at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5180)
                                                                                at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4620)
                                                                                at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4673)
                                                                                at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4639)
                                                                                at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4781)
                                                                                at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4647)
                                                                                at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4838)
                                                                                at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4620)
                                                                                at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4673)
                                                                                at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4639)
                                                                                at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4647)
                                                                                at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4620)
                                                                                at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7306)
                                                                                at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7184)
                                                                                at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7145)
                                                                                at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7416)
                                                                                at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                                at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                at android.os.MessageQueue.next(MessageQueue.java:323)
                                                                                at android.os.Looper.loop(Looper.java:143)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by andresoviedo** [comment]
Should be fixed in latest version. If it doesn't for you, please reopen issue.
