### ISSUE TITLE
Why are some DAE files loaded deffer from the original format?

### ISSUE THREAD

**Issue by cancanw** [andresoviedo/android-3D-model-viewer#57]
Why are some DAE files loaded deffer from the original format?

**Comment by andresoviedo** [comment]
Thanks for the feedback.

Collada files have different information depending on what tool is used to generate them (blender, 3d max, etc) . I just adapted the app to work with the free examples I found on Internet.  

However, I should try to fix files and code.

**Comment by andresoviedo** [comment]
Last spec as of now: https://www.khronos.org/files/collada_spec_1_5.pdf

**Comment by andresoviedo** [comment]
If you have any model not working please attach it so I can fix the app.

**Comment by cancanw** [comment]
Sorry, I can't give you the document.
The DAE file is exported by the C4d tool.

**Comment by cancanw** [comment]
This DAE file comes with its own color.

**Comment by cancanw** [comment]
<contributor>
            <authoring_tool>CINEMA4D 18.011 COLLADA Exporter</authoring_tool>
        </contributor>

**Comment by andresoviedo** [comment]
Would you please describe your issue?   
Is there any error log?

**Comment by cancanw** [comment]
2018-10-10 10:04:53.878 1022-1310/? E/LightsService: Light requested not available on this device. 2
2018-10-10 10:04:59.189 1312-1355/? E/rutils: releaseProcess gCount = 2
2018-10-10 10:05:03.820 1022-1154/? E/LightsService: Light requested not available on this device. 2
2018-10-10 10:05:03.842 1022-1310/? E/LightsService: Light requested not available on this device. 2
2018-10-10 10:05:23.167 1022-1154/? E/LightsService: Light requested not available on this device. 2
2018-10-10 10:05:24.317 1022-1310/? E/LightsService: Light requested not available on this device. 2
2018-10-10 10:05:27.549 7224-8183/org.andresoviedo.dddmodel2 E/ColladaLoader: Problem loading skinning/skeleton data
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List org.andresoviedo.util.xml.XmlNode.getChildren(java.lang.String)' on a null object reference
        at org.andresoviedo.android_3d_model_engine.services.collada.loader.SkinLoader.extractSkinData(SkinLoader.java:31)
        at org.andresoviedo.android_3d_model_engine.services.collada.loader.ColladaLoader.loadColladaModel(ColladaLoader.java:166)
        at org.andresoviedo.android_3d_model_engine.services.collada.loader.ColladaLoader.buildAnimatedModel(ColladaLoader.java:50)
        at org.andresoviedo.android_3d_model_engine.services.collada.ColladaLoaderTask.build(ColladaLoaderTask.java:28)
        at org.andresoviedo.android_3d_model_engine.services.LoaderTask.doInBackground(LoaderTask.java:59)
        at org.andresoviedo.android_3d_model_engine.services.LoaderTask.doInBackground(LoaderTask.java:17)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2018-10-10 10:05:27.551 7224-8183/org.andresoviedo.dddmodel2 E/SceneLoader: Attempt to invoke interface method 'boolean java.util.Map.containsKey(java.lang.Object)' on a null object reference
    java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Map.containsKey(java.lang.Object)' on a null object reference
        at org.andresoviedo.android_3d_model_engine.services.collada.loader.GeometryLoader.readPositions(GeometryLoader.java:156)
        at org.andresoviedo.android_3d_model_engine.services.collada.loader.GeometryLoader.readRawData(GeometryLoader.java:96)
        at org.andresoviedo.android_3d_model_engine.services.collada.loader.GeometryLoader.extractModelData(GeometryLoader.java:68)
        at org.andresoviedo.android_3d_model_engine.services.collada.loader.ColladaLoader.loadColladaModel(ColladaLoader.java:180)
        at org.andresoviedo.android_3d_model_engine.services.collada.loader.ColladaLoader.buildAnimatedModel(ColladaLoader.java:50)
        at org.andresoviedo.android_3d_model_engine.services.collada.ColladaLoaderTask.build(ColladaLoaderTask.java:28)
        at org.andresoviedo.android_3d_model_engine.services.LoaderTask.doInBackground(LoaderTask.java:59)
        at org.andresoviedo.android_3d_model_engine.services.LoaderTask.doInBackground(LoaderTask.java:17)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2018-10-10 10:05:29.189 1312-1355/? E/rutils: releaseProcess gCount = 2
2018-10-10 10:05:33.306 1022-1154/? E/LightsService: Light requested not available on this device. 2

**Comment by cancanw** [comment]
My DAE file was exported by the CINEMA4D 18.011 COLLADA Exporter tool. It has its own color.and no img. The previous version 2.0.2 can be loaded, but it become deformed and no colors after loading . Now version 2.2.0 is loaded with an error report. The error message toast is as follows. The error log is shown in the previous message.

There was a problem building the model: Attempt to invoke interface method 'boolean java.util.Map.containsKey(java.lang.Object)' on a null object reference

**Comment by andresoviedo** [comment]
Thanks for the log.  I think I know where the problem is.
Your model does not have "controllers".  Although that's not a problem.
However, the GeometryLoader is trying to get weight data from that non-existing controller.
I will fix it in the next commit

**Comment by andresoviedo** [comment]
Hello there.
I've just release a new major version on collada dae and engine #81 
Please give it a try. If you still find issues please reopen the ticket.
Kind regards
