### ISSUE TITLE
Crash on the simulator when loading some 3D models in DAE format.

### ISSUE THREAD

**Issue by cancanw** [andresoviedo/android-3D-model-viewer#81]
for (XmlNode controller : controllersNode.getChildren("controller")) {  
This line of code has a null pointer。

-------------------------------------------------------------------------------------------------------
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List xxx.util.xml.XmlNode.getChildren(java.lang.String)' on a null object reference
        at com.yiside.quote.dae.model3D.services.collada.loader.SkinLoader.extractSkinData(SkinLoader.java:28)
        at com.yiside.quote.dae.model3D.services.collada.loader.ColladaLoader.loadColladaModel(ColladaLoader.java:213)
        at com.yiside.quote.dae.model3D.services.collada.loader.ColladaLoader.buildAnimatedModel(ColladaLoader.java:55)
        at com.yiside.quote.dae.model3D.services.collada.loader.ColladaLoader.access$000(ColladaLoader.java:43)
        at com.yiside.quote.dae.model3D.services.collada.loader.ColladaLoader$ColladaLoaderTask.build(ColladaLoader.java:186)
        at com.yiside.quote.dae.model3D.controller.LoaderTask.doInBackground(LoaderTask.java:87)
        at com.yiside.quote.dae.model3D.controller.LoaderTask.doInBackground(LoaderTask.java:19)

**Comment by jiulincheng** [comment]
I got a same issues

**Comment by andresoviedo** [comment]
Hi @cancanw   @jiulincheng   thanks for your feedback.
I can try to analyze what is the missing information.
Please, if it's possible share your model so it's easier to find the error.
Regards

**Comment by ruanbaojun1105** [comment]
I got a same issues.

thanks~

[test.zip](https://github.com/andresoviedo/android-3D-model-viewer/files/3360796/test.zip)

**Comment by andresoviedo** [comment]
Hello guys.  

I'm working on this issue with the test example you provided.  I confirm there are 2 major issues

1 - this dae model in particular has no skinning data but a visual scene with 693 nodes. 

that's a very large uniform array to fit on all GPU.
to fix this we may need to upgrade to OpenGL ES 3.1 to support large joint structures
i fixed it augmenting the vertex shader buffer size from 60 to 700 but that's won't work for everyone.
https://stackoverflow.com/questions/20647207/glsl-replace-large-uniform-int-array-with-buffer-or-texture

2 - the app does not position them on world space correctly:  
working on it... :SS

Kind regards
