### ISSUE TITLE
dae load failed

### ISSUE THREAD

**Issue by ZhengzhongSun** [andresoviedo/android-3D-model-viewer#88]
I load your dae files in this repo successfully, but when I load my own dae files. There are some errors. Could you give some advice to me? Thank you!

`2018-12-27 11:43:24.607 9028-12425/org.andresoviedo.dddmodel2 E/SceneLoader: Attempt to invoke interface method 'boolean java.util.Map.containsKey(java.lang.Object)' on a null object reference
    java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Map.containsKey(java.lang.Object)' on a null object reference
        at org.andresoviedo.android_3d_model_engine.services.collada.loader.GeometryLoader.readPositions(GeometryLoader.java:156)
        at org.andresoviedo.android_3d_model_engine.services.collada.loader.GeometryLoader.readRawData(GeometryLoader.java:96)
        at org.andresoviedo.android_3d_model_engine.services.collada.loader.GeometryLoader.extractModelData(GeometryLoader.java:68)
        at org.andresoviedo.android_3d_model_engine.services.collada.loader.ColladaLoader.loadColladaModel(ColladaLoader.java:180)
        at org.andresoviedo.android_3d_model_engine.services.collada.loader.ColladaLoader.buildAnimatedModel(ColladaLoader.java:50)
        at org.andresoviedo.android_3d_model_engine.services.collada.ColladaLoaderTask.build(ColladaLoaderTask.java:27)
        at org.andresoviedo.android_3d_model_engine.services.LoaderTask.doInBackground(LoaderTask.java:59)
        at org.andresoviedo.android_3d_model_engine.services.LoaderTask.doInBackground(LoaderTask.java:17)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
`

Here is my dae file.
[baby_groot.zip](https://github.com/andresoviedo/android-3D-model-viewer/files/2711377/baby_groot.zip)

**Comment by LinLiCh** [comment]
I have same error.

**Comment by andresoviedo** [comment]
Hi @ZhengzhongSun  @LinLiCh .   Thanks for your feedback. I'll take a look asap.

**Comment by andresoviedo** [comment]
Fixed in latest version. Please try.
Regards
